use std::os::raw::c_uchar;

use global_hotkey::hotkey::Code as MyCode;
use global_hotkey::hotkey::Modifiers as MyModifiers;

#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub enum HotKeyState {
    Pressed = 0,
    Released = 1,
    Cancelled = 2,
}
pub fn digit_to_mycode(arr: c_uchar) -> Option<MyCode> {
    Some(match arr {
        0 => MyCode::Backquote,
        1 => MyCode::Backslash,
        2 => MyCode::BracketLeft,
        3 => MyCode::BracketRight,
        4 => MyCode::Comma,
        5 => MyCode::Digit0,
        6 => MyCode::Digit1,
        7 => MyCode::Digit2,
        8 => MyCode::Digit3,
        9 => MyCode::Digit4,
        10 => MyCode::Digit5,
        11 => MyCode::Digit6,
        12 => MyCode::Digit7,
        13 => MyCode::Digit8,
        14 => MyCode::Digit9,
        15 => MyCode::Equal,
        16 => MyCode::IntlBackslash,
        17 => MyCode::IntlRo,
        18 => MyCode::IntlYen,
        19 => MyCode::KeyA,
        20 => MyCode::KeyB,
        21 => MyCode::KeyC,
        22 => MyCode::KeyD,
        23 => MyCode::KeyE,
        24 => MyCode::KeyF,
        25 => MyCode::KeyG,
        26 => MyCode::KeyH,
        27 => MyCode::KeyI,
        28 => MyCode::KeyJ,
        29 => MyCode::KeyK,
        30 => MyCode::KeyL,
        31 => MyCode::KeyM,
        32 => MyCode::KeyN,
        33 => MyCode::KeyO,
        34 => MyCode::KeyP,
        35 => MyCode::KeyQ,
        36 => MyCode::KeyR,
        37 => MyCode::KeyS,
        38 => MyCode::KeyT,
        39 => MyCode::KeyU,
        40 => MyCode::KeyV,
        41 => MyCode::KeyW,
        42 => MyCode::KeyX,
        43 => MyCode::KeyY,
        44 => MyCode::KeyZ,
        45 => MyCode::Minus,
        46 => MyCode::Period,
        47 => MyCode::Quote,
        48 => MyCode::Semicolon,
        49 => MyCode::Slash,
        50 => MyCode::AltLeft,
        51 => MyCode::AltRight,
        52 => MyCode::Backspace,
        53 => MyCode::CapsLock,
        54 => MyCode::ContextMenu,
        55 => MyCode::ControlLeft,
        56 => MyCode::ControlRight,
        57 => MyCode::Enter,
        58 => MyCode::MetaLeft,
        59 => MyCode::MetaRight,
        60 => MyCode::ShiftLeft,
        61 => MyCode::ShiftRight,
        62 => MyCode::Space,
        63 => MyCode::Tab,
        64 => MyCode::Convert,
        65 => MyCode::KanaMode,
        66 => MyCode::Lang1,
        67 => MyCode::Lang2,
        68 => MyCode::Lang3,
        69 => MyCode::Lang4,
        70 => MyCode::Lang5,
        71 => MyCode::NonConvert,
        72 => MyCode::Delete,
        73 => MyCode::End,
        74 => MyCode::Help,
        75 => MyCode::Home,
        76 => MyCode::Insert,
        77 => MyCode::PageDown,
        78 => MyCode::PageUp,
        79 => MyCode::ArrowDown,
        80 => MyCode::ArrowLeft,
        81 => MyCode::ArrowRight,
        82 => MyCode::ArrowUp,
        83 => MyCode::NumLock,
        84 => MyCode::Numpad0,
        85 => MyCode::Numpad1,
        86 => MyCode::Numpad2,
        87 => MyCode::Numpad3,
        88 => MyCode::Numpad4,
        89 => MyCode::Numpad5,
        90 => MyCode::Numpad6,
        91 => MyCode::Numpad7,
        92 => MyCode::Numpad8,
        93 => MyCode::Numpad9,
        94 => MyCode::NumpadAdd,
        95 => MyCode::NumpadBackspace,
        96 => MyCode::NumpadClear,
        97 => MyCode::NumpadClearEntry,
        98 => MyCode::NumpadComma,
        99 => MyCode::NumpadDecimal,
        100 => MyCode::NumpadDivide,
        101 => MyCode::NumpadEnter,
        102 => MyCode::NumpadEqual,
        103 => MyCode::NumpadHash,
        104 => MyCode::NumpadMemoryAdd,
        105 => MyCode::NumpadMemoryClear,
        106 => MyCode::NumpadMemoryRecall,
        107 => MyCode::NumpadMemoryStore,
        108 => MyCode::NumpadMemorySubtract,
        109 => MyCode::NumpadMultiply,
        110 => MyCode::NumpadParenLeft,
        111 => MyCode::NumpadParenRight,
        112 => MyCode::NumpadStar,
        113 => MyCode::NumpadSubtract,
        114 => MyCode::Escape,
        115 => MyCode::Fn,
        116 => MyCode::FnLock,
        117 => MyCode::PrintScreen,
        118 => MyCode::ScrollLock,
        119 => MyCode::Pause,
        120 => MyCode::BrowserBack,
        121 => MyCode::BrowserFavorites,
        122 => MyCode::BrowserForward,
        123 => MyCode::BrowserHome,
        124 => MyCode::BrowserRefresh,
        125 => MyCode::BrowserSearch,
        126 => MyCode::BrowserStop,
        127 => MyCode::Eject,
        128 => MyCode::LaunchApp1,
        129 => MyCode::LaunchApp2,
        130 => MyCode::LaunchMail,
        131 => MyCode::MediaPlayPause,
        132 => MyCode::MediaSelect,
        133 => MyCode::MediaStop,
        134 => MyCode::MediaTrackNext,
        135 => MyCode::MediaTrackPrevious,
        136 => MyCode::Power,
        137 => MyCode::Sleep,
        138 => MyCode::AudioVolumeDown,
        139 => MyCode::AudioVolumeMute,
        140 => MyCode::AudioVolumeUp,
        141 => MyCode::WakeUp,
        142 => MyCode::Hyper,
        143 => MyCode::Super,
        144 => MyCode::Turbo,
        145 => MyCode::Abort,
        146 => MyCode::Resume,
        147 => MyCode::Suspend,
        148 => MyCode::Again,
        149 => MyCode::Copy,
        150 => MyCode::Cut,
        151 => MyCode::Find,
        152 => MyCode::Open,
        153 => MyCode::Paste,
        154 => MyCode::Props,
        155 => MyCode::Select,
        156 => MyCode::Undo,
        157 => MyCode::Hiragana,
        158 => MyCode::Katakana,
        159 => MyCode::Unidentified,
        160 => MyCode::F1,
        161 => MyCode::F2,
        162 => MyCode::F3,
        163 => MyCode::F4,
        164 => MyCode::F5,
        165 => MyCode::F6,
        166 => MyCode::F7,
        167 => MyCode::F8,
        168 => MyCode::F9,
        169 => MyCode::F10,
        170 => MyCode::F11,
        171 => MyCode::F12,
        172 => MyCode::F13,
        173 => MyCode::F14,
        174 => MyCode::F15,
        175 => MyCode::F16,
        176 => MyCode::F17,
        177 => MyCode::F18,
        178 => MyCode::F19,
        179 => MyCode::F20,
        180 => MyCode::F21,
        181 => MyCode::F22,
        182 => MyCode::F23,
        183 => MyCode::F24,
        184 => MyCode::F25,
        185 => MyCode::F26,
        186 => MyCode::F27,
        187 => MyCode::F28,
        188 => MyCode::F29,
        189 => MyCode::F30,
        190 => MyCode::F31,
        191 => MyCode::F32,
        192 => MyCode::F33,
        193 => MyCode::F34,
        194 => MyCode::F35,
        195 => MyCode::BrightnessDown,
        196 => MyCode::BrightnessUp,
        197 => MyCode::DisplayToggleIntExt,
        198 => MyCode::KeyboardLayoutSelect,
        199 => MyCode::LaunchAssistant,
        200 => MyCode::LaunchControlPanel,
        201 => MyCode::LaunchScreenSaver,
        202 => MyCode::MailForward,
        203 => MyCode::MailReply,
        204 => MyCode::MailSend,
        205 => MyCode::MediaFastForward,
        206 => MyCode::MediaPause,
        207 => MyCode::MediaPlay,
        208 => MyCode::MediaRecord,
        209 => MyCode::MediaRewind,
        210 => MyCode::MicrophoneMuteToggle,
        211 => MyCode::PrivacyScreenToggle,
        212 => MyCode::SelectTask,
        213 => MyCode::ShowAllWindows,
        214 => MyCode::ZoomToggle,
        _ => return None,
    })
}
// #[repr(C)]
// #[derive(Debug, Clone, Copy, PartialEq)]
// pub enum MyModifiers {
//     ALT = 0,
//     AltGraph = 1,
//     CapsLock = 2,
//     Control = 3,
//     Fn = 4,
//     FnLock = 5,
//     Meta = 6,
//     NumLock = 7,
//     ScrollLock = 8,
//     Shift = 9,
//     Symbol = 10,
//     SymboLock = 11,
//     Hyper = 12,
//     Super = 13,
// }

/// 将 u8 数字安全地转换为 Modifiers 枚举
pub fn digit_to_modifier(value: c_uchar) -> Option<MyModifiers> {
    Some(match value {
        0 => MyModifiers::ALT,
        1 => MyModifiers::ALT_GRAPH,
        2 => MyModifiers::CAPS_LOCK,
        3 => MyModifiers::CAPS_LOCK,
        4 => MyModifiers::FN,
        5 => MyModifiers::FN_LOCK,
        6 => MyModifiers::META,
        7 => MyModifiers::NUM_LOCK,
        8 => MyModifiers::SCROLL_LOCK,
        9 => MyModifiers::SHIFT,
        10 => MyModifiers::SYMBOL,
        11 => MyModifiers::SYMBOL_LOCK,
        12 => MyModifiers::HYPER,
        13 => MyModifiers::SUPER,
        _ => return None,
    })
}

#[cfg(test)]
mod test {
    use crate::code::*;

    #[test]
    fn reflect() {
        assert_eq!(digit_to_mycode(0), Some(MyCode::Backquote));
        assert_eq!(digit_to_mycode(214), Some(MyCode::ZoomToggle));
    }
}
