use std::os::raw::c_uchar;

use global_hotkey::hotkey::Code;
use global_hotkey::hotkey::Modifiers;

use crate::error::Status;

#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum MyHotKeyState {
    Pressed = 0,
    Released = 1,
}
impl From<MyHotKeyState> for c_uchar {
    fn from(value: MyHotKeyState) -> Self {
        value as Self
    }
}
impl TryFrom<c_uchar> for MyHotKeyState {
    type Error = Status;

    fn try_from(value: c_uchar) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(MyHotKeyState::Pressed),
            1 => Ok(MyHotKeyState::Released),
            _ => Err(Status::Fail),
        }
    }
}

pub fn digit_to_mycode(arr: c_uchar) -> Option<Code> {
    Some(match arr {
        0 => Code::Backquote,
        1 => Code::Backslash,
        2 => Code::BracketLeft,
        3 => Code::BracketRight,
        4 => Code::Comma,
        5 => Code::Digit0,
        6 => Code::Digit1,
        7 => Code::Digit2,
        8 => Code::Digit3,
        9 => Code::Digit4,
        10 => Code::Digit5,
        11 => Code::Digit6,
        12 => Code::Digit7,
        13 => Code::Digit8,
        14 => Code::Digit9,
        15 => Code::Equal,
        16 => Code::IntlBackslash,
        17 => Code::IntlRo,
        18 => Code::IntlYen,
        19 => Code::KeyA,
        20 => Code::KeyB,
        21 => Code::KeyC,
        22 => Code::KeyD,
        23 => Code::KeyE,
        24 => Code::KeyF,
        25 => Code::KeyG,
        26 => Code::KeyH,
        27 => Code::KeyI,
        28 => Code::KeyJ,
        29 => Code::KeyK,
        30 => Code::KeyL,
        31 => Code::KeyM,
        32 => Code::KeyN,
        33 => Code::KeyO,
        34 => Code::KeyP,
        35 => Code::KeyQ,
        36 => Code::KeyR,
        37 => Code::KeyS,
        38 => Code::KeyT,
        39 => Code::KeyU,
        40 => Code::KeyV,
        41 => Code::KeyW,
        42 => Code::KeyX,
        43 => Code::KeyY,
        44 => Code::KeyZ,
        45 => Code::Minus,
        46 => Code::Period,
        47 => Code::Quote,
        48 => Code::Semicolon,
        49 => Code::Slash,
        50 => Code::AltLeft,
        51 => Code::AltRight,
        52 => Code::Backspace,
        53 => Code::CapsLock,
        54 => Code::ContextMenu,
        55 => Code::ControlLeft,
        56 => Code::ControlRight,
        57 => Code::Enter,
        58 => Code::MetaLeft,
        59 => Code::MetaRight,
        60 => Code::ShiftLeft,
        61 => Code::ShiftRight,
        62 => Code::Space,
        63 => Code::Tab,
        64 => Code::Convert,
        65 => Code::KanaMode,
        66 => Code::Lang1,
        67 => Code::Lang2,
        68 => Code::Lang3,
        69 => Code::Lang4,
        70 => Code::Lang5,
        71 => Code::NonConvert,
        72 => Code::Delete,
        73 => Code::End,
        74 => Code::Help,
        75 => Code::Home,
        76 => Code::Insert,
        77 => Code::PageDown,
        78 => Code::PageUp,
        79 => Code::ArrowDown,
        80 => Code::ArrowLeft,
        81 => Code::ArrowRight,
        82 => Code::ArrowUp,
        83 => Code::NumLock,
        84 => Code::Numpad0,
        85 => Code::Numpad1,
        86 => Code::Numpad2,
        87 => Code::Numpad3,
        88 => Code::Numpad4,
        89 => Code::Numpad5,
        90 => Code::Numpad6,
        91 => Code::Numpad7,
        92 => Code::Numpad8,
        93 => Code::Numpad9,
        94 => Code::NumpadAdd,
        95 => Code::NumpadBackspace,
        96 => Code::NumpadClear,
        97 => Code::NumpadClearEntry,
        98 => Code::NumpadComma,
        99 => Code::NumpadDecimal,
        100 => Code::NumpadDivide,
        101 => Code::NumpadEnter,
        102 => Code::NumpadEqual,
        103 => Code::NumpadHash,
        104 => Code::NumpadMemoryAdd,
        105 => Code::NumpadMemoryClear,
        106 => Code::NumpadMemoryRecall,
        107 => Code::NumpadMemoryStore,
        108 => Code::NumpadMemorySubtract,
        109 => Code::NumpadMultiply,
        110 => Code::NumpadParenLeft,
        111 => Code::NumpadParenRight,
        112 => Code::NumpadStar,
        113 => Code::NumpadSubtract,
        114 => Code::Escape,
        115 => Code::Fn,
        116 => Code::FnLock,
        117 => Code::PrintScreen,
        118 => Code::ScrollLock,
        119 => Code::Pause,
        120 => Code::BrowserBack,
        121 => Code::BrowserFavorites,
        122 => Code::BrowserForward,
        123 => Code::BrowserHome,
        124 => Code::BrowserRefresh,
        125 => Code::BrowserSearch,
        126 => Code::BrowserStop,
        127 => Code::Eject,
        128 => Code::LaunchApp1,
        129 => Code::LaunchApp2,
        130 => Code::LaunchMail,
        131 => Code::MediaPlayPause,
        132 => Code::MediaSelect,
        133 => Code::MediaStop,
        134 => Code::MediaTrackNext,
        135 => Code::MediaTrackPrevious,
        136 => Code::Power,
        137 => Code::Sleep,
        138 => Code::AudioVolumeDown,
        139 => Code::AudioVolumeMute,
        140 => Code::AudioVolumeUp,
        141 => Code::WakeUp,
        142 => Code::Hyper,
        143 => Code::Super,
        144 => Code::Turbo,
        145 => Code::Abort,
        146 => Code::Resume,
        147 => Code::Suspend,
        148 => Code::Again,
        149 => Code::Copy,
        150 => Code::Cut,
        151 => Code::Find,
        152 => Code::Open,
        153 => Code::Paste,
        154 => Code::Props,
        155 => Code::Select,
        156 => Code::Undo,
        157 => Code::Hiragana,
        158 => Code::Katakana,
        159 => Code::Unidentified,
        160 => Code::F1,
        161 => Code::F2,
        162 => Code::F3,
        163 => Code::F4,
        164 => Code::F5,
        165 => Code::F6,
        166 => Code::F7,
        167 => Code::F8,
        168 => Code::F9,
        169 => Code::F10,
        170 => Code::F11,
        171 => Code::F12,
        172 => Code::F13,
        173 => Code::F14,
        174 => Code::F15,
        175 => Code::F16,
        176 => Code::F17,
        177 => Code::F18,
        178 => Code::F19,
        179 => Code::F20,
        180 => Code::F21,
        181 => Code::F22,
        182 => Code::F23,
        183 => Code::F24,
        184 => Code::F25,
        185 => Code::F26,
        186 => Code::F27,
        187 => Code::F28,
        188 => Code::F29,
        189 => Code::F30,
        190 => Code::F31,
        191 => Code::F32,
        192 => Code::F33,
        193 => Code::F34,
        194 => Code::F35,
        195 => Code::BrightnessDown,
        196 => Code::BrightnessUp,
        197 => Code::DisplayToggleIntExt,
        198 => Code::KeyboardLayoutSelect,
        199 => Code::LaunchAssistant,
        200 => Code::LaunchControlPanel,
        201 => Code::LaunchScreenSaver,
        202 => Code::MailForward,
        203 => Code::MailReply,
        204 => Code::MailSend,
        205 => Code::MediaFastForward,
        206 => Code::MediaPause,
        207 => Code::MediaPlay,
        208 => Code::MediaRecord,
        209 => Code::MediaRewind,
        210 => Code::MicrophoneMuteToggle,
        211 => Code::PrivacyScreenToggle,
        212 => Code::SelectTask,
        213 => Code::ShowAllWindows,
        214 => Code::ZoomToggle,
        _ => return None,
    })
}

/// 将 u8 数字安全地转换为 Modifiers 枚举
pub fn digit_to_modifier(value: c_uchar) -> Option<Modifiers> {
    Some(match value {
        0 => Modifiers::ALT,
        1 => Modifiers::ALT_GRAPH,
        2 => Modifiers::CAPS_LOCK,
        3 => Modifiers::CONTROL,
        4 => Modifiers::FN,
        5 => Modifiers::FN_LOCK,
        6 => Modifiers::META,
        7 => Modifiers::NUM_LOCK,
        8 => Modifiers::SCROLL_LOCK,
        9 => Modifiers::SHIFT,
        10 => Modifiers::SYMBOL,
        11 => Modifiers::SYMBOL_LOCK,
        12 => Modifiers::HYPER,
        13 => Modifiers::SUPER,
        _ => return None,
    })
}

#[cfg(test)]
mod test {
    use crate::code::*;

    #[test]
    fn reflect() {
        assert_eq!(digit_to_mycode(0), Some(Code::Backquote));
        assert_eq!(digit_to_mycode(214), Some(Code::ZoomToggle));
        assert_eq!(MyHotKeyState::Pressed, (0 as c_uchar).try_into().unwrap())
    }
}
